name: SFTP Deploy
on: 
  push:
    branches:
      - dev
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: Install LFTP
        run: sudo apt install lftp
      - name: Configure LFTP
        run: mkdir ~/.lftp && echo "set ssl:verify-certificate false\n\nset sftp:auto-confirm true" >> ~/.lftp/rc
      - name: Upload Folder
        run: lftp sftp://${{ secrets.DEV_FTP_USER }}:${{ secrets.DEV_FTP_PASSWORD }}@${{ secrets.DEV_FTP_HOST }}:2222 -e "put -O /git-actions/ ./index.html"
