name: SFTP Deploy
on: 
  push:
    branches:
      - dev
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.DEV_FTP_HOST }}
          username: ${{ secrets.DEV_FTP_USER }}
          password: ${{ secrets.DEV_FTP_PASSWORD }}
          protocol: ftps
          port: 2222
          server-dir: ./git-actions/
