on: 
  push:
    branches:
      - main 
name: Production SFTP Deploy
jobs:
  prod-sftp-deploy:
    name: Production SFTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Compile CURL from source
      run: ./.github/scripts/build-curl-sftp.sh
      shell: bash
    - name: Sync files
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: sftp://${{ secrets.MASTER_FTP_HOST }}:2222
        user: ${{ secrets.MASTER_FTP_USER }}
        password: ${{ secrets.MASTER_FTP_PASSWORD }}
